# Generated by Django 2.1.3 on 2018-11-11 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelwithme', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Traveller',
        ),
    ]
