# Generated by Django 2.1.3 on 2018-11-18 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelwithme', '0003_traveller'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trip',
        ),
        migrations.DeleteModel(
            name='TripRequest',
        ),
    ]
