# Generated by Django 2.1.2 on 2018-11-20 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelwithme', '0005_trip_triprequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triprequest',
            name='initiator',
        ),
        migrations.RemoveField(
            model_name='triprequest',
            name='trip_id',
        ),
        migrations.DeleteModel(
            name='TripRequest',
        ),
    ]
