# Generated by Django 2.1.2 on 2018-11-20 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelwithme', '0006_auto_20181120_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelwithme.Traveller')),
                ('trip_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelwithme.Trip')),
            ],
        ),
    ]
