# Generated by Django 2.1.2 on 2018-11-22 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelwithme', '0009_triprequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='status',
            field=models.CharField(default='open', max_length=20),
            preserve_default=False,
        ),
    ]
