# Generated by Django 2.1.2 on 2018-11-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelwithme', '0010_trip_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveller',
            name='avatar',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
